### PR TITLE
Enable Broker Authentication usign SASL mechanism

### PR DESCRIPTION
**Pull request by rmarting**
This PR implements the #34 issue, but only focused in the SASL authentication mechanisms (nothing about TLS or secured connections). 

This implementation is based on this [documentation](https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.4/html-single/using_amq_streams_on_rhel/index#sasl_authentication). Including the feature of enable different listeners and identify which one use for the inter-broker connections.

Using an inter-broker listener is a good pattern to split the traffic between consumers/producers and the internal broker. This feature covers the case of an authenticated listener too.

PS: This PR was implemented as an extension of the PR #33 (this is way some of the commits are described here).

### CODE REVIEW

**Comment by rmarting** [comment]
@guidograzioli @rpelisse What do you think?

**Comment by rmarting** [comment]
Added an extension to manage the authentication in the Kafka Connect cluster. Otherwise the Kafka connect will not be able to connect to an authenticated Kafka cluster managed by this collection.

**Comment by rpelisse** [comment]
Superseeded by https://github.com/ansible-middleware/amq_streams/pull/43

**Comment by rmarting** [comment]
Glad to see that my contributions are now merged into the `main` branch after the amazing review of my colleague @rpelisse. A great step forward of this collection.

**Comment by Neustradamus** [comment]
@rmarting, @rpelisse: Good job!

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/ansible-middleware/amq_streams/pull/35
- https://github.com/ansible-middleware/amq_streams/pull/43

**Pull request closed without merging**
