### PR TITLE
📝 Describe zk and bk groups

### PR DESCRIPTION
**Pull request by rmarting**
@rpelisse I would like to propose this commit to improve the documentation with the new variables to identify the zk and bk groups.

### CODE REVIEW

**Comment by rmarting** [comment]
@rpelisse I don't know if you were aware about this PR ... it is a PR for your PR, but I can't see it in the main branch. I think you merged first your PR and later this one, so this commit was not already merged into the `main` branch.

**Comment by rpelisse** [comment]
Oh, I think I know what happened. This PR has NOTHING to do with Describe zk and bk groups, but, when I created the PR, I had not rebased, so the first commit was "Describ zk and bk groups", which became the name of the PR.
I've renamed the PR, because we generate changelog from them, so it needed to be acurate.

**Comment by rpelisse** [comment]
Ok, I know what happened (I think). i'll cherry pick this commit into the main branch.

**Comment by rpelisse** [comment]
@rmarting Done. Can you double check that other commits / PR from you has not been overlooked? Thanks!

**Comment by rmarting** [comment]
Everything is good! Thanks for your help.

**Pull request merged**
